{
    'name': 'TruCalc Orders',
    'version': '1.23',
    'author': 'TruCalc',
    'license': 'LGPL-3',
    'category': 'Services',
    'summary': 'Evaluation Order Management',
    'depends': [
        'base',
        'mail',
        'portal',
    ],
    'data': [
        'security/trucalc_security.xml',
        'security/ir.model.access.csv',
        'data/order_sequence.xml',
        'data/vendor_authorization_cron.xml',
        'data/document_tags.xml',
        'views/vendor_portal_provision_views.xml',
        'views/order_decline_wizard_views.xml',
        'views/fee_change_request_views.xml',
        'views/bank_invoice_views.xml',
        'views/bank_invoice_report.xml',
        'views/reviewer_assignment_wizard_views.xml',
        'views/valuation_revision_wizard_views.xml',
        'views/bid_request_wizard_views.xml',
        'views/vendor_engagement_wizard_views.xml',
        'views/vendor_engagement_decision_wizard_views.xml',
        'views/vendor_views.xml',
        'views/res_users_views.xml',
        'views/evaluation_order_views.xml',
        'views/vendor_deliverable_views.xml',
        'views/document_views.xml',
        'views/document_tag_views.xml',
        'views/service_area_views.xml',
        'views/negotiated_fee_views.xml',
        'views/bid_views.xml',
        'views/vendor_portal_templates.xml',
        'views/bank_branding_templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'trucalc_orders/static/src/js/inspection_phone_format.js',
            'trucalc_orders/static/src/js/bank_draft_service_area.js',
            'trucalc_orders/static/src/scss/trucalc_tokens.scss',
            'trucalc_orders/static/src/scss/bank_portal.scss',
            'trucalc_orders/static/src/scss/trucalc_login.scss',
        ],
        'web.assets_backend': [
            'trucalc_orders/static/src/js/inspection_phone_format.js',
            'trucalc_orders/static/src/js/inspection_phone_blur_field.js',
            'trucalc_orders/static/src/xml/inspection_phone_blur_field.xml',
            'trucalc_orders/static/src/js/many2one_autosave_field.js',
            'trucalc_orders/static/src/scss/vendor_responses.scss',
        ],
    },
    'installable': True,
    'application': True,
}
