{
    'name': 'TruCalc Orders',
    'version': '1.12',
    'author': 'TruCalc',
    'license': 'LGPL-3',
    'category': 'Services',
    'summary': 'Evaluation Order Management',
    'depends': [
        'base',
        'mail',
        'portal',
    ],
    'data': [
        'security/trucalc_security.xml',
        'security/ir.model.access.csv',
        'data/order_sequence.xml',
        'data/vendor_authorization_cron.xml',
        'views/vendor_portal_provision_views.xml',
        'views/order_decline_wizard_views.xml',
        'views/bid_request_wizard_views.xml',
        'views/vendor_engagement_wizard_views.xml',
        'views/evaluation_order_views.xml',
        'views/vendor_views.xml',
        'views/document_views.xml',
        'views/bid_views.xml',
        'views/vendor_portal_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'trucalc_orders/static/src/scss/vendor_responses.scss',
        ],
    },
    'installable': True,
    'application': True,
}
